---
abstract: 'Fast SNMP data poller daemon, with storage and graphing'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YATG
requires:
  Class::Data::Inheritable: 0
  DBI: 0
  Data::Printer: 0
  Exporter: 0
  File::Basename: 0
  File::Copy: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::stat: 0
  FindBin: 0
  Lingua::EN::Inflect: 0
  Log::Dispatch::Syslog: 0
  Module::MultiConf: 0.0301
  Net::Netmask: 0
  POSIX: 0
  Readonly: 0
  Regexp::Common: 0
  SNMP: 0
  SNMP::Effective: 0
  Scriptalicious: 0
  Symbol: 0
  Sys::Syslog: 0.25
  Time::HiRes: 0
  YAML::XS: 0
  base: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=YATG
  homepage: https://github.com/ollyg/YATG/wiki
  repository: git://github.com/ollyg/YATG.git
version: 5.20002
